### ISSUE TITLE
Try `hwdec=vulkan`

### ISSUE THREAD

**Issue by DeadNews** [DeadNews/mpv-config#11]
https://github.com/DeadNews/mpv-config/blob/cf71867a226791c2ff0fa61fff5d8637e33407a8/mpv/mpv.nb.conf#L11

Blocked by:

> You need Mesa 23.1.X*, ffmepg 6.1 (unreleased), libplacebo v6 (released but no distro ships it yet due to VLC breaking). You can build all of those yourself to get vulkan support.
> 
> * While it may work on 23.1, it may be buggy, 23.2 should contain all the vulkan related changes

_Originally posted by @llyyr in https://github.com/mpv-player/mpv/issues/12011#issuecomment-1648073543_

**Comment by DeadNews** [comment]
_Device does not support the VK_KHR_video_decode_queue extension!_

**Comment by DeadNews** [comment]
Blocked by:
_Device does not support the VK_KHR_video_decode_queue extension!_

**Comment by llyyr** [comment]
You need to set `RADV_PERFTEST=video_decode` in your environment to expose the video decode extensions

**Comment by DeadNews** [comment]
@llyyr 
Thanks. It works.

https://github.com/mpv-player/mpv/issues/11739
